"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv():
    """Carga variables desde `.env` en la raíz del proyecto (no versionar .env)."""
    path = BASE_DIR / '.env'
    if not path.is_file():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('\'"')
        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Definir DJANGO_SECRET_KEY en el entorno o en `.env` (ver `.env.example`).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-set-DJANGO_SECRET_KEY-in-env',
)
# Ajuste para probar commit


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'true').lower() in ('1', 'true', 'yes')

# Evita "Invalid HTTP_HOST" en local y permite enlaces de recuperación con 127.0.0.1 o localhost.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver'] + [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()
]

# En producción acepta cualquier host y confía en dominios HTTPS
if not DEBUG:
    ALLOWED_HOSTS += ['*']
    # Siempre incluir wildcards de Railway más cualquier dominio extra en CSRF_TRUSTED_ORIGINS
    _extra_trusted = [
        f'https://{h.strip()}'
        for h in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
        if h.strip()
    ]
    CSRF_TRUSTED_ORIGINS = [
        'https://*.up.railway.app',
        'https://*.railway.app',
    ] + _extra_trusted
    # Asegurar cookies seguras detrás del proxy de Railway
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ]


# Application definition

INSTALLED_APPS = [
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.NoCacheAuthenticatedMiddleware',
    'users.middleware.ModuloBloqueoMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.carrito_publico',
                'users.context_processors.notificaciones_no_leidas',
            ],
            'builtins': ['users.templatetags.money_filters'],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

_DB_URL = os.environ.get('DATABASE_URL') or (
    f"postgresql://{os.environ.get('POSTGRES_USER','postgres')}"
    f":{os.environ.get('POSTGRES_PASSWORD','101606')}"
    f"@{os.environ.get('POSTGRES_HOST','127.0.0.1')}"
    f":{os.environ.get('POSTGRES_PORT','5432')}"
    f"/{os.environ.get('POSTGRES_DB','ROS_db')}"
)

DATABASES = {
    'default': dj_database_url.config(
        default=_DB_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
}
#subir

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

AUTH_USER_MODEL = 'users.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Recuperación de contraseña: en desarrollo el correo se imprime en la consola del servidor.
# En producción configura SMTP (p. ej. EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD).

# --- CONFIGURACIÓN DE CORREO ACTUALIZADA ---
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND') or 'django.core.mail.backends.smtp.EmailBackend'

if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend' or os.environ.get('SMTP_HOST'):
    EMAIL_HOST = os.environ.get('SMTP_HOST') or 'smtp.gmail.com'
    EMAIL_PORT = int(os.environ.get('SMTP_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('SMTP_USER') or 'jeisonpinilla14@gmail.com'
    EMAIL_HOST_PASSWORD = os.environ.get('SMTP_PASSWORD') or 'welk kamo aise qrsf' # Tu código de 16 letras
    EMAIL_USE_TLS = os.environ.get('SMTP_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
    EMAIL_USE_SSL = os.environ.get('SMTP_USE_SSL', 'false').lower() in ('1', 'true', 'yes')
else:
    # Si cambias el backend a consola en el .env, caerá aquí
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = (
    os.environ.get('EMAIL_FROM')
    or f"Olla y Sazón <{EMAIL_HOST_USER}>" 
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

PASSWORD_RESET_TIMEOUT = 180  # 3 minutos (solo pruebas)

# --- SendPulse (correos masivos) ---
SENDPULSE_CLIENT_ID = os.environ.get('SENDPULSE_CLIENT_ID', '')
SENDPULSE_CLIENT_SECRET = os.environ.get('SENDPULSE_CLIENT_SECRET', '')
SENDPULSE_FROM_EMAIL = os.environ.get('SENDPULSE_FROM_EMAIL', 'OllaSazon@gmail.com')
SENDPULSE_FROM_NAME = os.environ.get('SENDPULSE_FROM_NAME', 'Olla y Sazón')
SENDPULSE_LIST_ID = int(os.environ.get('SENDPULSE_LIST_ID', '633081'))
